language: java
jdk:
  - openjdk8
install: true
script:
  - mvn clean
  - mvn install
after_success:
  - rm -rf push
  - mkdir push
  - cp ./target/*.jar ./push/
  - mkdir devbukkit
  - cp ./target/*.jar ./devbukkit/
  - rm -f ./devbukkit/original-*.jar
  - rm -f ./devbukkit/*-javadoc.jar
  - rm -f ./devbukkit/*-shaded.jar
  - rm -f ./devbukkit/*-sources.jar
  - rm -f ./target/original-*.jar
  - ls ./devbukkit -1 | grep ".jar$" > jarname.txt
  - git clone https://$Github_token@github.com/Ghost-chu/BinaryRepository.git
  - mkdir -p ./BinaryRepository/QuickShop-Reremake/$TRAVIS_BUILD_NUMBER
  - mkdir -p ./BinaryRepository/QuickShop-Reremake/$TRAVIS_BUILD_NUMBER/target
  - cp ./target/* ./BinaryRepository/QuickShop-Reremake/$TRAVIS_BUILD_NUMBER/target
  - echo -e "== Built by Travis-CI ==\nBuild Number [$TRAVIS_BUILD_NUMBER]\nBuild Type [$TRAVIS_EVENT_TYPE]\nTag [$TRAVIS_TAG]\nCommit [$TRAVIS_COMMIT] - [TRAVIS_COMMIT_MESSAGE]" > BUILDINFO
  - cd BinaryRepository
  - git add .
  - git commit -m "Auto update by Bot"
  - git push --force
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $Github_token
  file:
    - ./push/*
  file_glob: true
  on:
    tags: true
after_deploy:
  - chmod +x deploy.sh
  - ./deploy.sh $Curse_token