language: java
jdk:
- oraclejdk8
install: true
script:
- mvn clean
- mvn install
after_success:
- rm -rf push
- mkdir push
- cp ./target/*.jar ./push/
- rm -f ./push/original*.jar
- rm -f ./push/*shaded.jar
- ls ./push -1 | grep ".jar$" > jarname.txt
deploy:
    skip_cleanup: true
    provider: releases
    api_key:
        secure: $Github_token
    file:
    - ./push/*
    file_glob: true
    on:
        tags: true
after_deploy:
- chmod +x depoly.sh
- ./depoly.sh $Curse_token