language: java
jdk:
- oraclejdk8
install: true
script:
- mvn clean
- mvn install
after_success:
- rm -rf push
- mkdir push
- cp ./target/*.jar ./push/
- ls ./push -1 | grep ".jar$" > jarname.txt
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-SNAPSHOT-\#$TRAVIS_BUILD_NUMBER-$(git log --format=%h -1)-$(date +'%Y%m%d%H%M%S')}
deploy:
#Release
-   provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
        secure: $Github_token
    file:
    - ./push/*
    script: ./deploy.sh
    file_glob: true
    on:
        tags: true
#Pre-Release
-   provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
        secure: $Github_token
    file:
    - ./push/*
    file_glob: true
    prerelease: true
    on:
        tags: false
#after_deploy:
#- chmod +x after_deploy.sh
#- ./after_deploy.sh $Curse_token