language: java
jdk:
  - oraclejdk8
install: true
script:
  - mvn clean
  - mvn install
after_success:
  - rm -rf push
  - mkdir push
  - cp ./target/*.jar ./push/
  - ls ./push -1 | grep ".jar$" > jarname.txt
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $Github_token
  file:
    - ./push/*
  file_glob: true
  on:
    tags: true
after_deploy:
  - sh deploy.sh $Curse_token