language: java
jdk:
- oraclejdk8
install: true
script:
- mvn clean
- mvn install
after_success:
- rm -rf push
- mkdir push
- cp ./target/*.jar ./push/
- mkdir devbukkit
- cp ./target/*.jar ./devbukkit/
- rm -f ./devbukkit/original-*.jar
- rm -f ./devbukkit/*-javadoc.jar
- rm -f ./devbukkit/*-shaded.jar
- rm -f ./devbukkit/*-sources.jar
- ls ./devbukkit -1 | grep ".jar$" > jarname.txt
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)-$TRAVIS_BUILD_NUMBER}
deploy:
#Release
-   provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
        secure: $Github_token
    file:
    - ./push/*
    script: bash upload2bukkit.sh
    file_glob: true
    on:
        tags: true
#Pre-Release
-   provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
        secure: $Github_token
    file:
    - ./push/*
    file_glob: true
    prerelease: true
#after_deploy:
#- chmod +x after_deploy.sh
#- ./after_deploy.sh $Curse_token